# -*- coding: utf-8 -*-
from pathlib import Path
etnx = Path(r"C:\Users\a8071\Projects\nameanalyz\assets\index-eTNXNndF.js").read_text(encoding="utf-8")
kw5 = Path(r"C:\Users\a8071\Projects\nameanalyz\assets\index-kw5.js").read_text(encoding="utf-8")
out = Path(r"C:\Users\a8071\Projects\nameanalyz\_ohang_v4_check.txt")
chunks = []
i = etnx.find("EnglishName.tsx:602")
chunks.append("EN602=" + etnx[i : i + 900])
i = etnx.find("EnglishName.tsx:470")
chunks.append("EN470=" + etnx[i - 500 : i + 200])
i = kw5.find("Home.tsx:rankB")
chunks.append("RANK=" + kw5[i : i + 500])
i = kw5.find("(()=>{const isCeo")
chunks.append("IIFE_HEAD=" + kw5[i : i + 500])
i = kw5.find("ohangCall")
chunks.append("CALL=" + kw5[i : i + 280])
i = etnx.find("EnglishName.tsx:domGen")
chunks.append("DOMGEN=" + etnx[i : i + 220])
i = etnx.find("학창시절 왕따")
chunks.append("BULLY=" + (etnx[i : i + 280] if i >= 0 else "NONE"))
i = etnx.find("EnglishName.tsx:680")
chunks.append("EN680=" + etnx[i : i + 400] if i >= 0 else "NONE")
out.write_text("\n\n====\n\n".join(chunks), encoding="utf-8")
print("bytes", out.stat().st_size)
